# Generated by Django 4.2.7 on 2023-12-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_autor_alter_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nadpis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
