# Generated by Django 4.2.7 on 2024-01-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_nadpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nadpis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
